MATRIX_FILES = [
    "c30.sparse.bin",
    "c65.sparse.bin",
    "c90.sparse.bin",
    "c115.sparse.bin",
    "bcsstk29.mtx",
    "bcsstk30.mtx",
    "bcsstk31.mtx",
    "bcsstk32.mtx",
    "bcsstk33.mtx",
    "pcrystk02.mtx",
    "pcrystk03.mtx",
    "gupta1.mtx",
    "gupta2.mtx",
    "gupta3.mtx",
    "pli.mtx",
    "pfinan512.mtx",
    "3dtube.mtx",
    "gearbox.mtx",
    "struct3.mtx",
    "pkustk01.mtx",
    "pkustk02.mtx",
    "pkustk03.mtx",
    "pkustk04.mtx",
    "pkustk05.mtx",
    "pkustk06.mtx",
    "pkustk07.mtx",
    "pkustk08.mtx",
    "pkustk09.mtx",
    "pkustk10.mtx",
    "pkustk11.mtx",
    "pkustk12.mtx",
    "pkustk13.mtx",
    "pkustk14.mtx",
    "Stanford.mtx",
    "Stanford_Berkeley.mtx",
    "copter2.mtx",
    "crplat2.mtx",
    "fcondp2.mtx",
    "fullb.mtx",
    "halfb.mtx",
    "opt1.mtx",
    "ramage02.mtx",
    "srb1.mtx",
    "trdheim.mtx",
    "troll.mtx",
    "tsyl201.mtx",
    "ex3sta1.mtx",
    "ins2.mtx",
    "lp1.mtx",
    "mip1.mtx",
    "net50.mtx",
    "net75.mtx",
    "net100.mtx",
    "net125.mtx",
    "net150.mtx",
    "net4-1.mtx",
    "pattern1.mtx",
    "pf2177.mtx",
    "IMDB.mtx",
    "NotreDame_actors.mtx",
    "NotreDame_www.mtx",
    "patents.mtx",
    "nw14.mtx",
    "wb-edu.mtx",
    "wikipedia-20051105.mtx",
    "wikipedia-20060925.mtx",
    "wikipedia-20061104.mtx",
    "wikipedia-20070206.mtx",
    "s4dkt3m2.mtx",
    "bibd_17_8.mtx",
    "bibd_18_9.mtx",
    "bibd_19_9.mtx",
    "bibd_20_10.mtx",
    "bibd_22_8.mtx",
    "HFE18_96_in.mtx",
    "kneser_10_4_1.mtx",
    "wheel_601.mtx",
    "connectus.mtx",
    "12month1.mtx",
    "soc-LiveJournal1.mtx",
    "soc-Epinions1.mtx",
    "soc-Slashdot0811.mtx",
    "soc-Slashdot0902.mtx",
    "wiki-Talk.mtx",
    "cit-Patents.mtx",
    "web-BerkStan.mtx",
    "web-Google.mtx",
    "web-NotreDame.mtx",
    "web-Stanford.mtx",
    "amazon0312.mtx",
    "amazon0302.mtx",
    "amazon0505.mtx",
    "amazon0601.mtx",
    "roadNet-CA.mtx",
    "roadNet-PA.mtx",
    "roadNet-TX.mtx",
    "as-Skitter.mtx",
    "flickr.mtx",
    "wave.mtx",
    "debr.mtx",
    "cnr-2000.mtx",
    "in-2004.mtx",
    "eu-2005.mtx",
    "amazon-2008.mtx",
    "ljournal-2008.mtx",
    "hollywood-2009.mtx",
    "dblp-2010.mtx",    
    "webbase-2001.mtx",
    "uk-2002.mtx",
    "indochina-2004.mtx",
    "it-2004.mtx",
    "arabic-2005.mtx",
    "sk-2005.mtx",
    "uk-2005.mtx",
    "caidaRouterLevel.mtx",
    "road_central.mtx",
    "road_usa.mtx",
    "citationCiteseer.mtx",
    "coAuthorsCiteseer.mtx",
    "coAuthorsDBLP.mtx",
    "coPapersCiteseer.mtx",
    "coPapersDBLP.mtx",
    "delaunay_n17.mtx",
    "delaunay_n18.mtx",
    "delaunay_n19.mtx",
    "delaunay_n20.mtx",
    "delaunay_n21.mtx",
    "delaunay_n22.mtx",
    "delaunay_n23.mtx",
    "delaunay_n24.mtx",
    "hugebubbles-00000.mtx",
    "hugebubbles-00010.mtx",
    "hugebubbles-00020.mtx",
    "hugetrace-00000.mtx",
    "hugetrace-00010.mtx",
    "hugetrace-00020.mtx",
    "hugetric-00000.mtx",
    "hugetric-00010.mtx",
    "hugetric-00020.mtx",
    "adaptive.mtx",
    "channel-500x100x100-b050.mtx",
    "packing-500x100x100-b050.mtx",
    "venturiLevel3.mtx",
    "rgg_n_2_15_s0.mtx",
    "rgg_n_2_16_s0.mtx",
    "rgg_n_2_17_s0.mtx",
    "rgg_n_2_18_s0.mtx",
    "rgg_n_2_19_s0.mtx",
    "rgg_n_2_20_s0.mtx",
    "rgg_n_2_21_s0.mtx",
    "rgg_n_2_22_s0.mtx",
    "rgg_n_2_23_s0.mtx",
    "rgg_n_2_24_s0.mtx",
    "asia_osm.mtx",
    "belgium_osm.mtx",
    "europe_osm.mtx",
    "germany_osm.mtx",
    "great-britain_osm.mtx",
    "italy_osm.mtx",
    "netherlands_osm.mtx",
    "144.mtx",
    "598a.mtx",
    "auto.mtx",
    "fe_ocean.mtx",
    "fe_rotor.mtx",
    "fe_tooth.mtx",
    "m14b.mtx",
    "G_n_pin_pout.mtx",
    "preferentialAttachment.mtx",
    "smallworld.mtx",
    "333SP.mtx",
    "AS365.mtx",
    "M6.mtx",
    "NACA0015.mtx",
    "NLR.mtx",
    "vsp_bcsstk30_500sep_10in_1Kout.mtx",
    "vsp_bump2_e18_aa01_model1_crew1.mtx",
    "vsp_finan512_scagr7-2c_rlfddd.mtx",
    "vsp_mod2_pgp2_slptsk.mtx",
    "vsp_msc10848_300sep_100in_1Kout.mtx",
    "vsp_vibrobox_scagr7-2c_rlfddd.mtx",
    "mycielskian13.mtx",
    "mycielskian14.mtx",
    "mycielskian15.mtx",
    "mycielskian16.mtx",
    "mycielskian17.mtx",
    "mycielskian18.mtx",
    "mycielskian19.mtx",
    "mycielskian20.mtx",
    "com-Amazon.mtx",
    "com-DBLP.mtx",
    "com-Friendster.mtx",
    "com-LiveJournal.mtx",
    "com-Orkut.mtx",
    "com-Youtube.mtx",
    "higgs-twitter.mtx",
    "loc-Gowalla.mtx",
    "soc-Pokec.mtx",
    "twitter7.mtx",
    "wiki-topcats.mtx",
    "kmer_A2a.mtx",
    "kmer_P1a.mtx",
    "kmer_U1a.mtx",
    "kmer_V1r.mtx",
    "kmer_V2a.mtx",
    #"AGATHA_2015.mtx",
]


# Map detailed problem types
MATRIX_TYPES={
    "c30.sparse.bin":"Integer Factorization",
    "c65.sparse.bin":"Integer Factorization",
    "c90.sparse.bin":"Integer Factorization",
    "c115.sparse.bin":"Integer Factorization",
    "bcsstk29.mtx":"Structural Engineering",
    "bcsstk30.mtx":"Structural Engineering",
    "bcsstk31.mtx":"Structural Engineering",
    "bcsstk32.mtx":"Structural Engineering",
    "bcsstk33.mtx":"Structural Engineering",
    "pcrystk02.mtx":"Structural Engineering",
    "pcrystk03.mtx":"Structural Engineering",
    "gupta1.mtx":"Linear Programming",
    "gupta2.mtx":"Linear Programming",
    "gupta3.mtx":"Linear Programming",
    "pli.mtx":"Linear Programming",
    "pfinan512.mtx":"Linear Programming",
    "3dtube.mtx":"Structural Engineering",
    "gearbox.mtx":"Mechanical Engineering",
    "struct3.mtx":"Structural Engineering",
    "pkustk01.mtx":"Structural Engineering",
    "pkustk02.mtx":"Structural Engineering",
    "pkustk03.mtx":"Structural Engineering",
    "pkustk04.mtx":"Structural Engineering",
    "pkustk05.mtx":"Structural Engineering",
    "pkustk06.mtx":"Structural Engineering",
    "pkustk07.mtx":"Structural Engineering",
    "pkustk08.mtx":"Structural Engineering",
    "pkustk09.mtx":"Structural Engineering",
    "pkustk10.mtx":"Structural Engineering",
    "pkustk11.mtx":"Structural Engineering",
    "pkustk12.mtx":"Structural Engineering",
    "pkustk13.mtx":"Structural Engineering",
    "pkustk14.mtx":"Structural Engineering",
    "Stanford.mtx":"Graph",
    "Stanford_Berkeley.mtx":"Graph",
    "copter2.mtx":"Graph",
    "crplat2.mtx":"Graph",
    "fcondp2.mtx":"Graph",
    "fullb.mtx":"Graph",
    "halfb.mtx":"Graph",
    "opt1.mtx":"Graph",
    "ramage02.mtx":"Graph",
    "srb1.mtx":"Graph",
    "trdheim.mtx":"Graph",
    "troll.mtx":"Graph",
    "tsyl201.mtx":"Graph",
    "ex3sta1.mtx":"Graph",
    "ins2.mtx":"Graph",
    "lp1.mtx":"Linear Programming",
    "mip1.mtx":"Mixed Integer Programming",
    "net50.mtx":"Network",
    "net75.mtx":"Network",
    "net100.mtx":"Network",
    "net125.mtx":"Network",
    "net150.mtx":"Network",
    "net4-1.mtx":"Network",
    "pattern1.mtx":"Pattern Recognition",
    "pf2177.mtx":"Pattern Recognition",
    "IMDB.mtx":"Social Network",
    "NotreDame_actors.mtx":"Social Network",
    "NotreDame_www.mtx":"Social Network",
    "patents.mtx":"Citation Network",
    "nw14.mtx":"Network",
    "wb-edu.mtx":"Web Graph",
    "wikipedia-20051105.mtx":"Web Graph",
    "wikipedia-20060925.mtx":"Web Graph",
    "wikipedia-20061104.mtx":"Web Graph",
    "wikipedia-20070206.mtx":"Web Graph",
    "s4dkt3m2.mtx":"Graph",
    "bibd_17_8.mtx":"Combinatorial Problem",
    "bibd_18_9.mtx":"Combinatorial Problem",
    "bibd_19_9.mtx":"Combinatorial Problem",
    "bibd_20_10.mtx":"Combinatorial Problem",
    "bibd_22_8.mtx":"Combinatorial Problem",
    "HFE18_96_in.mtx":"Combinatorial Problem",
    "kneser_10_4_1.mtx":"Combinatorics",
    "wheel_601.mtx":"Combinatorics",
    "connectus.mtx":"Graph",
    "12month1.mtx":"Time Series",
    "soc-LiveJournal1.mtx":"Social Network",
    "soc-Epinions1.mtx":"Social Network",
    "soc-Slashdot0811.mtx":"Social Network",
    "soc-Slashdot0902.mtx":"Social Network",
    "wiki-Talk.mtx":"Social Network",
    "cit-Patents.mtx":"Citation Network",
    "web-BerkStan.mtx":"Web Graph",
    "web-Google.mtx":"Web Graph",
    "web-NotreDame.mtx":"Web Graph",
    "web-Stanford.mtx":"Web Graph",
    "amazon0312.mtx":"Web Graph",
    "amazon0302.mtx":"Web Graph",
    "amazon0505.mtx":"Web Graph",
    "amazon0601.mtx":"Web Graph",
    "roadNet-CA.mtx":"Transportation Network",
    "roadNet-PA.mtx":"Transportation Network",
    "roadNet-TX.mtx":"Transportation Network",
    "as-Skitter.mtx":"Network",
    "flickr.mtx":"Social Network",
    "wave.mtx":"Finite Element Analysis",
    "debr.mtx":"Graph",
    "cnr-2000.mtx":"Web Graph",
    "in-2004.mtx":"Web Graph",
    "eu-2005.mtx":"Web Graph",
    "amazon-2008.mtx":"Web Graph",
    "ljournal-2008.mtx":"Social Network",
    "hollywood-2009.mtx":"Social Network",
    "dblp-2010.mtx":"Citation Network",
    "webbase-2001.mtx":"Web Graph",
    "uk-2002.mtx":"Web Graph",
    "indochina-2004.mtx":"Web Graph",
    "it-2004.mtx":"Web Graph",
    "arabic-2005.mtx":"Web Graph",
    "sk-2005.mtx":"Web Graph",
    "uk-2005.mtx":"Web Graph",
    "caidaRouterLevel.mtx":"Network",
    "road_central.mtx":"Transportation Network",
    "road_usa.mtx":"Transportation Network",
    "citationCiteseer.mtx":"Citation Network",
    "coAuthorsCiteseer.mtx":"Citation Network",
    "coAuthorsDBLP.mtx":"Citation Network",
    "coPapersCiteseer.mtx":"Citation Network",
    "coPapersDBLP.mtx":"Citation Network",
    "delaunay_n17.mtx":"Undirected Graph",
    "delaunay_n18.mtx":"Undirected Graph",
    "delaunay_n19.mtx":"Undirected Graph",
    "delaunay_n20.mtx":"Undirected Graph",
    "delaunay_n21.mtx":"Undirected Graph",
    "delaunay_n22.mtx":"Undirected Graph",
    "delaunay_n23.mtx":"Undirected Graph",
    "delaunay_n24.mtx":"Undirected Graph",
    "hugebubbles-00000.mtx":"Undirected Graph",
    "hugebubbles-00010.mtx":"Undirected Graph",
    "hugebubbles-00020.mtx":"Undirected Graph",
    "hugetrace-00000.mtx":"Undirected Graph",
    "hugetrace-00010.mtx":"Undirected Graph",
    "hugetrace-00020.mtx":"Undirected Graph",
    "hugetric-00000.mtx":"Undirected Graph",
    "hugetric-00010.mtx":"Undirected Graph",
    "hugetric-00020.mtx":"Undirected Graph",
    "adaptive.mtx":"Undirected Graph",
    "channel-500x100x100-b050.mtx":"Undirected Graph",
    "packing-500x100x100-b050.mtx":"Undirected Graph",
    "venturiLevel3.mtx":"Undirected Graph",
    "rgg_n_2_15_s0.mtx":"Random Graph",
    "rgg_n_2_16_s0.mtx":"Random Graph",
    "rgg_n_2_17_s0.mtx":"Random Graph",
    "rgg_n_2_18_s0.mtx":"Random Graph",
    "rgg_n_2_19_s0.mtx":"Random Graph",
    "rgg_n_2_20_s0.mtx":"Random Graph",
    "rgg_n_2_21_s0.mtx":"Random Graph",
    "rgg_n_2_22_s0.mtx":"Random Graph",
    "rgg_n_2_23_s0.mtx":"Random Graph",
    "rgg_n_2_24_s0.mtx":"Random Graph",
    "asia_osm.mtx":"Geospatial",
    "belgium_osm.mtx":"Geospatial",
    "europe_osm.mtx":"Geospatial",
    "germany_osm.mtx":"Geospatial",
    "great-britain_osm.mtx":"Geospatial",
    "italy_osm.mtx":"Geospatial",
    "netherlands_osm.mtx":"Geospatial",
    "144.mtx":"Geospatial",
    "598a.mtx":"Geospatial",
    "auto.mtx":"Geospatial",
    "fe_ocean.mtx":"Finite Element Analysis",
    "fe_rotor.mtx":"Finite Element Analysis",
    "fe_tooth.mtx":"Finite Element Analysis",
    "m14b.mtx":"Finite Element Analysis",
    "G_n_pin_pout.mtx":"Graph",
    "preferentialAttachment.mtx":"Graph",
    "smallworld.mtx":"Graph",
    "333SP.mtx":"Graph",
    "AS365.mtx":"Graph",
    "M6.mtx":"Graph",
    "NACA0015.mtx":"Aerodynamics",
    "NLR.mtx":"Aerodynamics",
    "vsp_bcsstk30_500sep_10in_1Kout.mtx":"Structural Engineering",
    "vsp_bump2_e18_aa01_model1_crew1.mtx":"Structural Engineering",
    "vsp_finan512_scagr7-2c_rlfddd.mtx":"Linear Programming",
    "vsp_mod2_pgp2_slptsk.mtx":"Structural Engineering",
    "vsp_msc10848_300sep_100in_1Kout.mtx":"Structural Engineering",
    "vsp_vibrobox_scagr7-2c_rlfddd.mtx":"Structural Engineering",
    "mycielskian13.mtx":"Graph",
    "mycielskian14.mtx":"Graph",
    "mycielskian15.mtx":"Graph",
    "mycielskian16.mtx":"Graph",
    "mycielskian17.mtx":"Graph",
    "mycielskian18.mtx":"Graph",
    "mycielskian19.mtx":"Graph",
    "mycielskian20.mtx":"Graph",
    "com-Amazon.mtx":"Web Graph",
    "com-DBLP.mtx":"Citation Network",
    "com-Friendster.mtx":"Social Network",
    "com-LiveJournal.mtx":"Social Network",
    "com-Orkut.mtx":"Social Network",
    "com-Youtube.mtx":"Social Network",
    "higgs-twitter.mtx":"Social Network",
    "loc-Gowalla.mtx":"Social Network",
    "soc-Pokec.mtx":"Social Network",
    "twitter7.mtx":"Social Network",
    "wiki-topcats.mtx":"Social Network",
    "kmer_A2a.mtx":"Combinatorics",
    "kmer_P1a.mtx":"Combinatorics",
    "kmer_U1a.mtx":"Combinatorics",
    "kmer_V1r.mtx":"Combinatorics",
    "kmer_V2a.mtx":"Combinatorics",
    #"AGATHA_2015.mtx":"Graph",
}

# Map main type
MAIN_TYPE={
    "Integer Factorization":"integer",
    "Structural Engineering":"structural",
    "Mechanical Engineering":"structural",
    "Finite Element Analysis":"structural",
    "Aerodynamics":"structural",
    "Linear Programming":"optimization",
    "Mixed Integer Programming":"optimization",
    "Graph":"undirected graph",
    "Random Graph":"random graph",
    "Combinatorics":"combinatorial",
    "Combinatorial Problem":"combinatorial",
    "Time Series":"optimization",
    "Pattern Recognition":"optimization",
    "Undirected Graph":"undirected graph",
    "Network":"undirected graph",
    "Social Network":"undirected graph",
    "Transportation Network":"undirected graph",
    "Citation Network":"directed graph",
    "Web Graph":"directed graph",
    "Geospatial":"structural",
}

